export const auctionActionTypes = {
  GET_AUCTION_DATA: 'GET_AUCTION_DATA',
  GET_AUCTION_DATA_SUCCESS: 'GET_AUCTION_DATA_SUCCESS',
  GET_AUCTION_DATA_ERROR: 'GET_AUCTION_DATA_ERROR',
};

export const auctionByIdActionTypes = {
  GET_AUCTION_BY_ID: 'GET_AUCTION_BY_ID',
  GET_AUCTION_BY_ID_SUCCESS: 'GET_AUCTION_BY_ID_SUCCESS',
  GET_AUCTION_BY_ID_ERROR: 'GET_AUCTION_BY_ID_ERROR',
};
