export const userActionTypes = {
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILED: 'GET_USER_FAILED',
  GET_USER_DATA_REQUESTED: 'GET_USER_REQUESTED',
  SET_FILTERED_LIST: 'SET_FILTERED_LIST',
  SET_PAGINATED_USER_LIST: 'SET_PAGINATED_USER_LIST',
};
